/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "files.h"

bool_t
xdr_files (XDR *xdrs, files *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->name, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->conteudo, MAXLEN,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nBytes))
		 return FALSE;
	return TRUE;
}
