/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILES_H_RPCGEN
#define _FILES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXLEN 262144

struct files {
	char name[256];
	char conteudo[MAXLEN];
	int nBytes;
};
typedef struct files files;

#define FILE_PROG 0x31230000
#define FILE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FILEPROC 1
extern  int * fileproc_1(files *, CLIENT *);
extern  int * fileproc_1_svc(files *, struct svc_req *);
extern int file_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FILEPROC 1
extern  int * fileproc_1();
extern  int * fileproc_1_svc();
extern int file_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_files (XDR *, files*);

#else /* K&R C */
extern bool_t xdr_files ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILES_H_RPCGEN */
